# Datastore directory path
datastore: /home/geth/.oasvlfy

# Keystore directory path
# When using a plaintext private key, it is not necessary.
keystore: /home/geth/.ethereum/keystore

wallets:
  # Wallet used by Verifier (Usually the same address as geth)
  signer:
    address: '0x'
    # password: /home/geth/.ethereum/password.txt

    # Use a plaintext private key
    # plain: '0x'

  # Wallet used by Submitter (gas is required)
  # submitter:
  #   address: '0x'

# Hub-Layer settings
hub_layer:
  chain_id: 9372
  rpc: wss://ws.testnet.oasys.games/

# Verse-Layer settings
verse_layer:
  discovery:
    endpoint: https://cdn.testnet.oasys.games/_oasvlfy/verse-layers.v1.json

# P2P node
p2p:
  listens:
    - /ip4/0.0.0.0/tcp/4101
    - /ip4/0.0.0.0/udp/4101/quic
  bootnodes:
    - /dns/verse-verifier01.testnet.oasys.games/tcp/4101/p2p/12D3KooWNyNfCGYx5kwnqmwB3iMNHtzJv1ZTUiiSNpfYhMjVMzSz
    - /dns/verse-verifier01.testnet.oasys.games/udp/4101/quic/p2p/12D3KooWNyNfCGYx5kwnqmwB3iMNHtzJv1ZTUiiSNpfYhMjVMzSz
  relay_client:
    enable: true

# Verification worker
verifier:
  enable: true
  wallet: signer

# Signature submitting worker
submitter:
  enable: false  # Only enable for Verse Builder
  targets:
    - chain_id: 420  # Chain ID of your Verse-Layer(testnet)
      wallet: submitter
